services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "10347:3000"
    volumes:
      # This persists your SQLite DB and your uploads
      - ./test-tracker-data:/app/test-tracker-data
    environment:
      - DATABASE_PATH=file:/app/test-tracker-data/test-tracker.sqlite
      - UPLOAD_PATH=/app/test-tracker-data/uploads
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - BEARER_TOKEN=${BEARER_TOKEN}
