services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    ports:
      - "3000:3000"
    volumes:
      # This persists your SQLite DB and your uploads
      - ./test-tracker-data:/app/test-tracker-data
    environment:
      - PORT=3000
      # Example: Tell your app where to find the DB file
      - DATABASE_PATH=/app/test-tracker-data/test-tracker.sqlite
      - UPLOAD_PATH=
    restart: always